### ISSUE TITLE
sample rate should be > 200ksps ?

### ISSUE THREAD

**Issue by DD4WH** [FrankBoesing/TeensyFMTransmitter#3]
Hi Frank!
my understanding of your wonderful code is very limited.

However, I think the whole code should run in a much higher sample rate.

We have a frequency deviation of +-75kHz, so we need at least 150kHz, better 200kHz of bandwidth for the FM audio signal.

Could you try running the code at an audio sample rate of > 200ksps ?

If I listen carefully to the audio quality, especially in silent moments of the music (I made some custom WAV files with Steely Dan music ;-)), I feel I could hear distortion/aliases in the higher audio frequs, so this could potentially be cured by a higher sample rate ?

But as I do not understand large parts of your code, this is pure speculation, but maybe worth trying it out ;-)

I used the code from 2021/01/23 10:00h CET

**Comment by FrankBoesing** [comment]
Good Idea. I'll next try to use a timer to directly trigger the DMA, then we can try to use a higher samplerate.

High frequencies: Is my code for the pre-emphasis correct? I took the de-emphasis from your code and swapped the factors.

A Question regarding the deviation: I thought the 75KHz is the sum - 75KHz/2 to the "left" and 75KHz/2 to the "right" ?  
It is directly connected to the volume problem in #4  So the volume can be fixed by using the correct frequency deviation (If I'm wrong with my assumption) - i'm using the half, currently.

I'll write a text of how it works in the next days. In short: It connects the Video-PLL to the MCLK-Output of I2S. There is a fixed divisor of 4, so the PLL uses 4 times the Frequency (i.e. 100MHz FM -> 400MHz PLL)    
For FM, this frequency gets modified by the calculated deviation factor. So ideally, a volume correction should not be needed(?)  
Quite possible there are some little bugs now, sooner or later we'll fix them ;)

**Comment by FrankBoesing** [comment]
(FM: "volume" is the same as the frequency deviation)

**Comment by DD4WH** [comment]
Yes, you are totally right and already fixed the problem: it is +-75kHz freq deviation, so 150 in total. And that also fixes the volume problem!
Pre-emphasis also seems to work now.
A text on how it works would be very much appreciated ! At the moment, no idea from my side . . . ;-)

Higher sample rate:
* play WAV at 44.1 ksps
* interpolate to 6 x 44.1 = 264.6 ksps
* lowpass filter

**Comment by FrankBoesing** [comment]
can be closed now.
